# Generated by Django 3.2.8 on 2021-11-10 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('hTeamScore', models.IntegerField(blank=True, null=True)),
                ('aTeamScore', models.IntegerField(blank=True, null=True)),
                ('goalScorers', models.CharField(max_length=300)),
                ('match_id', models.IntegerField()),
            ],
            options={
                'ordering': ['matchday'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('founded', models.IntegerField()),
                ('logo', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('number', models.IntegerField(null=True)),
                ('position', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=250)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.team')),
            ],
            options={
                'ordering': ('team__name', 'position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MatchPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeTeamScore', models.PositiveIntegerField()),
                ('awayTeamScore', models.PositiveIntegerField()),
                ('checked', models.BooleanField(default=False)),
                ('points', models.PositiveIntegerField(blank=True, null=True)),
                ('goalScorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='aTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='predictor.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='hTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='predictor.team'),
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='league_admin', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='league_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
