# Generated by Django 3.2.8 on 2021-10-31 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('hTeamScore', models.IntegerField(blank=True, null=True)),
                ('aTeamScore', models.IntegerField(blank=True, null=True)),
                ('match_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('founded', models.IntegerField()),
                ('logo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('number', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=250)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeTeamScore', models.PositiveIntegerField()),
                ('awayTeamScore', models.PositiveIntegerField()),
                ('checked', models.BooleanField(default=False)),
                ('result_points', models.PositiveIntegerField(blank=True, null=True)),
                ('scorer_points', models.PositiveIntegerField(blank=True, null=True)),
                ('goalScorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='aTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='predictor.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='goalScorers',
            field=models.ManyToManyField(blank=True, related_name='goal_scorers', to='predictor.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='hTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='predictor.team'),
        ),
    ]
