# Generated by Django 3.2.8 on 2021-10-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchprediction',
            name='result_points',
        ),
        migrations.RemoveField(
            model_name='matchprediction',
            name='scorer_points',
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
