# Generated by Django 3.2.8 on 2021-11-16 23:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='league',
            name='pin',
            field=models.IntegerField(default=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchevents',
            name='match',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='predictor.match'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchevents',
            name='team',
            field=models.ForeignKey(default='111', on_delete=django.db.models.deletion.CASCADE, to='predictor.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchevents',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
