# Generated by Django 3.2.8 on 2021-11-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20211116_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='rules',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
