# Generated by Django 3.2.8 on 2021-11-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_alter_match_matchday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
