# Generated by Django 3.2.8 on 2021-11-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_league_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='rules',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
