# Generated by Django 3.2.8 on 2021-11-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_alter_player_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
