# Generated by Django 3.2.8 on 2021-11-08 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_alter_player_player_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('team__name', 'position', 'name')},
        ),
        migrations.CreateModel(
            name='MatchEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.player')),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='goalScorers',
            field=models.ManyToManyField(blank=True, related_name='goal_scorers', to='predictor.MatchEvents'),
        ),
    ]
