# Generated by Django 3.2.8 on 2021-11-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0008_auto_20211108_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='goalScorers',
        ),
        migrations.AddField(
            model_name='match',
            name='goalScorers',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
