# Generated by Django 3.2.8 on 2021-11-08 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictor', '0009_auto_20211108_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['matchday']},
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='league_admin', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='league_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
