# Generated by Django 3.2.8 on 2021-11-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0010_auto_20211108_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='no_of_u',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
